// Americana pack, part 4 of 5: culture. Sports, music, screens, holidays,
// school, slang.
export default [
  ['Baseball', 'diamond|bat|Field of Dreams|cap|inside'],
  ['Touchdown', 'football|dance|spike|six'],
  ['Super Bowl', 'Sunday|commercials|halftime|ring'],
  ['Slam Dunk', 'basketball|contest|easy case|poster'],
  ['Hoop', 'basketball|hula|earring|Hoosiers'],
  ['Dunk', 'donut|basketball|tank|Dunkin'],
  ['Derby', 'Kentucky|hat|demolition|roller|Soap Box'],
  ['Rodeo', 'bull|clown|Drive|not my first'],
  ['Lasso', 'rope|Ted|Wonder Woman|cowboy'],
  ['Nascar', 'racing|Daytona|left turns|Talladega'],
  ['Daytona', '500|beach|Bike Week|arcade game'],
  ['Indy', '500|Jones|Indianapolis|music'],
  ['Pit', 'stop|crew|bull|peach|barbecue'],
  ['Marathon', 'Boston|26.2|Netflix|Man'],
  ['Tackle', 'football|box|fishing|the problem'],
  ['Huddle', 'football|up|House|meeting'],
  ['Blitz', 'football|London|chess|Blitzen'],
  ['Quarterback', 'sack|Monday morning|snap|Hail Mary'],
  ['Cheerleader', 'pom-poms|Bring It On|pyramid|cheerleader for'],
  ['Mascot', 'Phanatic|costume|Gritty|team'],
  ['Bleacher', 'seats|Report|Wrigley|bum'],
  ['Stadium', 'arena|Wrigley|Lambeau|rock concert'],
  ['Pennant', 'flag|race|World Series|college'],
  ['Rookie', 'card|of the Year|cop|mistake'],
  ['Draft', 'NFL|beer|breeze|first|dodger'],
  ['Playoff', 'October|beard|bracket|wild card'],
  ['Bracket', 'March Madness|square|tax|shelf'],
  ['Madness', 'March|Reefer|method|Max'],
  ['Umpire', 'strike|kill the|mask|blue'],
  ['Strike', 'baseball|bowling|union|gold|lightning'],
  ['Bowling', 'alley|Big Lebowski|pin|Green'],
  ['Golf', 'cart|Augusta|ball|Volkswagen'],
  ['Caddy', 'golf|Shack|tea|cart'],
  ['Surf', 'board|Beach Boys|and turf|web'],
  ['Skateboard', 'Tony Hawk|half-pipe|kickflip|Dogtown'],
  ['Wrestling', 'WWE|Hulk Hogan|arm|folding chair'],
  ['Frisbee', 'disc|golf|dog|Wham-O'],
  ['Cornhole', 'bags|boards|beanbag|tailgate'],
  ['Bass', 'fish|guitar|Pro Shops|drop|clef'],
  ['Trout', 'fish|fly fishing|Mike|brook'],
  ['Deer', 'hunting|season|John Deere|Bambi|headlights'],
  ['Jazz', 'Utah|New Orleans|hands|Age|Fest'],
  ['Blues', 'St. Louis|music|Brothers|jeans|got the'],
  ['Country', 'music|western|club|God and|road'],
  ['Rock', 'roll|Plymouth|Dwayne|Kid|bottom'],
  ['Banjo', 'bluegrass|Deliverance|Steve Martin|Kermit'],
  ['Fiddle', 'violin|Devil Went Down|Nero|fit as'],
  ['Guitar', 'Gibson|Fender|Hero|air'],
  ['Motown', 'Detroit|Records|Sound|Hitsville'],
  ['Anthem', 'national|Star-Spangled|Ayn Rand|Rage'],
  ['Banner', 'Star-Spangled|Bruce|ad|headline'],
  ['Hip-Hop', 'rap|Bronx|hooray|culture'],
  ['Grammy', 'award|grandma|gramophone|Grammys'],
  ['Jukebox', 'diner|Hero|musical|quarter'],
  ['Mixtape', 'cassette|Guardians|rap|road trip'],
  ['Woodstock', 'festival|Snoopy|1969|mud'],
  ['Band', 'marching|rubber|wedding|Aid|the Band'],
  ['Oscar', 'Award|Wilde|the Grouch|Mayer|de la Hoya'],
  ['Sitcom', 'laugh track|Friends|Seinfeld|thirty minutes'],
  ['Soap', 'opera|box|bar|derby'],
  ['Western', 'cowboy|Union|Great|omelet'],
  ['Cartoon', 'Saturday morning|Network|Looney|political'],
  ['Ticket', 'movie|speeding|golden|lottery'],
  ['Blockbuster', 'movie|Video|late fees|Netflix'],
  ['Late Night', 'talk show|Letterman|Conan|snack'],
  ['Game Show', 'Price is Right|Wheel|Feud|host'],
  ['Jeopardy', 'Trebek|what is|Double|double'],
  ['Wheel', 'of Fortune|steering|hamster|Ferris|reinvent'],
  ['Puppet', 'Muppets|master|sock|Sesame Street'],
  ['Sesame', 'Street|seed|open|oil'],
  ['Star Wars', 'Lucas|lightsaber|Force|Reagan'],
  ['Trek', 'Star|hike|mountain bike|Trekkie'],
  ['Jaws', 'shark|movie|of life|jawline'],
  ['Alien', 'E.T.|Sigourney|immigrant|Area 51'],
  ['Roswell', 'UFO|New Mexico|1947|TV show'],
  ['UFO', 'flying saucer|sighting|Roswell|unidentified'],
  ['Zombie', 'Walking Dead|Romero|Pittsburgh|apocalypse'],
  ['Batman', 'Gotham|Robin|Adam West|bat'],
  ['Marvel', 'comics|Captain|marvel at|Universe'],
  ['Captain', 'America|Crunch|Kirk|Kangaroo'],
  ['Hulk', 'Hogan|green|smash|Banner'],
  ['Ghost', 'town|Rider|writer|Casper|Swayze'],
  ['Thanksgiving', 'turkey|Pilgrims|parade|Black Friday|football'],
  ['Fourth', 'of July|quarter|wall|May the'],
  ['Halloween', 'costume|Michael Myers|candy|October'],
  ['Trick', 'or treat|magic|hat|turn a'],
  ['Costume', 'Halloween|party|jewelry|design'],
  ['Black Friday', 'shopping|doorbuster|Thanksgiving|deals'],
  ['Prom', 'dress|queen|promposal|Carrie'],
  ['Homecoming', 'game|queen|Spider-Man|float'],
  ['Yearbook', 'photo|signature|most likely to|senior'],
  ['Recess', 'playground|Supreme Court|Congress|cartoon'],
  ['Spelling Bee', 'National|i before e|Akeelah|Scripps'],
  ['Scout', 'Boy|Girl|cookies|talent|Mockingbird'],
  ['Camp', 'summer|fire|Rock|David|campy'],
  ['Detention', 'school|Breakfast Club|center|Saturday'],
  ['Locker', 'room|combination|Davy Jones|Hurt'],
  ['Arcade', 'games|Fire|Pac-Man|tokens'],
  ['Pinball', 'wizard|flipper|tilt|machine'],
  ['Comic', 'book|strip|con|stand-up'],
];
