// Americana pack, part 2 of 5: names that double. Presidents and founders
// whose surnames mean something else, icons, brands, and team names that are
// also ordinary words.
export default [
  ['Lincoln', 'president|car|tunnel|log|five|Nebraska'],
  ['Grant', 'president|fifty|scholarship|Hugh|take for granted'],
  ['Ford', 'president|car|Harrison|Theatre|river crossing'],
  ['Bush', 'president|shrub|band|beat around'],
  ['Carter', 'president|peanuts|Get Carter|Cash'],
  ['Hoover', 'president|dam|vacuum|J. Edgar'],
  ['Jackson', 'Andrew|Michael|twenty|Hole|Mississippi'],
  ['Madison', 'president|Square Garden|Avenue|Wisconsin|Splash'],
  ['Monroe', 'president|Marilyn|Doctrine|Louisiana'],
  ['Pierce', 'president|Hawkeye|ear|Brosnan'],
  ['Tyler', 'president|Perry|Durden|name'],
  ['Adams', 'president|Family|Douglas|apple'],
  ['Wilson', 'president|volleyball|Owen|Phillips'],
  ['Truman', 'president|Show|Capote|buck stops'],
  ['Kennedy', 'JFK|airport|Center|Camelot|Space Center'],
  ['Franklin', 'Ben|Aretha|hundred|stove|Turtle'],
  ['Hamilton', 'founder|ten|musical|Bermuda|Lewis'],
  ['Jefferson', 'president|Memorial|Airplane|nickel|The Jeffersons'],
  ['Roosevelt', 'Teddy|FDR|Room|Island|dime'],
  ['Eisenhower', 'Ike|interstate|jacket|D-Day'],
  ['Harrison', 'president|Ford|George|Beatle'],
  ['Arthur', 'president|King|aardvark|Fonzie'],
  ['Garfield', 'president|cat|lasagna|Monday'],
  ['Revere', 'Paul|midnight ride|Revere Ware|admire'],
  ['Hancock', 'John|signature|Tower|Herbie'],
  ['Crockett', 'Davy|coonskin|Alamo|Miami Vice'],
  ['Boone', 'Daniel|Pat|Farm|North Carolina'],
  ['Earhart', 'Amelia|pilot|Lockheed|vanished'],
  ['Edison', 'Thomas|bulb|New Jersey|phonograph'],
  ['Tesla', 'Nikola|car|coil|band'],
  ['Wright', 'brothers|Frank Lloyd|Kitty Hawk|right'],
  ['Bell', 'Alexander|Liberty|Taco|jar|Kristen'],
  ['Carnegie', 'Hall|Mellon|steel|library|Dale'],
  ['Rockefeller', 'Center|oil|Plaza|rich as'],
  ['Vanderbilt', 'university|Gloria|Commodore|Anderson Cooper'],
  ['Morgan', 'J.P.|Freeman|Captain|horse'],
  ['Heinz', 'ketchup|57|Field|Hall'],
  ['Hershey', 'chocolate|Pennsylvania|park|Kiss'],
  ['Disney', 'Walt|World|Land|Channel|Mickey'],
  ['Hilton', 'hotel|Paris|Head|Perez'],
  ['Marshall', 'Plan|Thurgood|amp|Eminem|store'],
  ['Elvis', 'King|Presley|Costello|Graceland|jumpsuit'],
  ['Marilyn', 'Monroe|Manson|blonde|subway grate'],
  ['Sinatra', 'Frank|Vegas|My Way|Ol Blue Eyes'],
  ['Jordan', 'Michael|river|country|Air|Hal'],
  ['Ruth', 'Babe|Baby Ruth|Bible|Dr. Ruth'],
  ['Mantle', 'Mickey|fireplace|earth|Yankees'],
  ['Cobb', 'Ty|salad|corn|Lee J.'],
  ['Ali', 'Muhammad|Baba|butterfly|Louisville'],
  ['Jackie', 'Robinson|Kennedy|Chan|Gleason'],
  ['Mickey', 'Mouse|Mantle|Rourke|slipped a'],
  ['Bugs', 'Bunny|insects|wiretap|whats up doc'],
  ['Homer', 'Simpson|home run|Odyssey|Alaska'],
  ['Rocky', 'Balboa|Mountains|road ice cream|Bullwinkle|Horror'],
  ['Superman', 'Metropolis|Krypton|Reeve|Smallville'],
  ['Barbie', 'doll|Malibu|movie|Ken'],
  ['Kermit', 'frog|Muppets|tea|Texas'],
  ['Snoopy', 'beagle|Red Baron|Peanuts|balloon'],
  ['Popeye', 'spinach|sailor|Chicken|forearms'],
  ['Betty', 'Boop|Crocker|White|Ugly'],
  ['Buddy', 'Holly|Elf|Guy|pal'],
  ['Bonnie', 'and Clyde|Raitt|Tyler|bonny'],
  ['Jesse', 'James|Owens|Ventura|Pinkman'],
  ['Levi', 'jeans|Strauss|tribe|Stadium'],
  ['Harley', 'Davidson|Quinn|hog|Street'],
  ['Chevy', 'Chase|truck|Malibu|like a rock'],
  ['Cadillac', 'car|Ranch|Escalade|the Cadillac of'],
  ['Jeep', 'Wrangler|WWII|Cherokee|off-road'],
  ['Coke', 'soda|Classic|Zero|polar bear|coal'],
  ['Nike', 'shoes|goddess|swoosh|missile'],
  ['Amazon', 'river|company|warrior|Prime|rainforest'],
  ['Boeing', 'planes|747|Seattle|Dreamliner'],
  ['Kodak', 'film|moment|Rochester|Black'],
  ['Zippo', 'lighter|Pennsylvania|click|zip'],
  ['Hallmark', 'cards|Channel|Christmas movie|of quality'],
  ['Spam', 'canned meat|email|Hawaii|Monty Python'],
  ['Twinkie', 'snack|defense|Zombieland|shelf life'],
  ['Colt', 'revolver|horse|Indianapolis|45'],
  ['Remington', 'rifle|typewriter|razor|Steele'],
  ['Winchester', 'rifle|Mystery House|cathedral|Supernatural'],
  ['Macy', 'parade|department store|Miracle on 34th|Gray'],
  ['Target', 'store|bullseye|practice|on'],
  ['Starbucks', 'coffee|Seattle|Moby-Dick|siren|pumpkin spice'],
  ['Budweiser', 'beer|Clydesdales|King of Beers|frogs'],
  ['Patriot', 'New England|missile|Act|colonial'],
  ['Ranger', 'Texas|Army|park|Power|Lone'],
  ['Giant', 'New York|San Francisco|Andre|beanstalk|Green'],
  ['Jet', 'New York|plane|ski|lag|Sharks'],
  ['Cardinal', 'bird|St. Louis|Arizona|church|direction|sin'],
  ['Charger', 'Los Angeles|phone|Dodge|horse'],
  ['Bronco', 'Denver|horse|Ford|bucking'],
  ['Dodger', 'Los Angeles|Brooklyn|draft|Artful'],
  ['Pirate', 'Pittsburgh|Caribbean|radio|software|arrr'],
  ['Penguin', 'Pittsburgh|bird|Batman|books|tuxedo'],
  ['Steeler', 'Pittsburgh|steel|Curtain|Terrible Towel'],
  ['Packer', 'Green Bay|cheesehead|Lambeau|meat'],
  ['Cowboy', 'Dallas|West|Bebop|boots|space'],
  ['Raven', 'Baltimore|Poe|bird|nevermore'],
  ['Eagle', 'bird|Philadelphia|Scout|golf|lunar module|band'],
  ['Bear', 'Chicago|animal|market|Yogi|Smokey'],
];
