// Americana pack, part 5 of 5: land, money, service, symbols, machines, the
// road West. Team names that are also animals live here.
export default [
  ['Bison', 'animal|national mammal|burger|Yellowstone'],
  ['Bald', 'eagle|head|tire|faced'],
  ['Moose', 'animal|lodge|Bullwinkle|Maine'],
  ['Gator', 'Florida|alligator|Gatorade|Burt Reynolds'],
  ['Coyote', 'Arizona|Wile E.|Ugly|howl'],
  ['Grizzly', 'Memphis|bear|Adams|Man'],
  ['Raccoon', 'trash panda|Rocket|mask|coonskin'],
  ['Skunk', 'stripe|Pepe Le Pew|Works|smell'],
  ['Hawk', 'Seattle|Atlanta|Tony|Hudson|Iowa'],
  ['Falcon', 'Atlanta|bird|Millennium|Maltese|Heavy'],
  ['Pelican', 'New Orleans|bird|Brief|Louisiana'],
  ['Duck', 'Oregon|Anaheim|Donald|tape|Daffy'],
  ['Bull', 'Chicago|market|Red|Durham|Sitting'],
  ['Ram', 'Los Angeles|Dodge|memory|animal|battering'],
  ['Tiger', 'LSU|Detroit|Woods|Tony|Bengal'],
  ['Panther', 'Carolina|Black|Pink|Florida'],
  ['Wolverine', 'Michigan|X-Men|animal|claws'],
  ['Longhorn', 'Texas|cattle|Steakhouse|hook em'],
  ['Rattlesnake', 'Diamondback|Gadsden|dont tread|desert'],
  ['Mustang', 'horse|Ford|P-51|Sally'],
  ['Redwood', 'tree|California|National Park|Endor'],
  ['Sequoia', 'tree|Toyota|National Park|Cherokee'],
  ['Maple', 'syrup|leaf|tree|Vermont'],
  ['Oak', 'tree|Ridge|barrel|Oakland'],
  ['Tornado', 'Alley|Wizard of Oz|twister|warning'],
  ['Twister', 'game|movie|tornado|Chubby Checker'],
  ['Hurricane', 'Miami|Carolina|lamp|cocktail|Rubin'],
  ['Blizzard', 'snow|Dairy Queen|1888|whiteout'],
  ['Thunder', 'Oklahoma City|storm|Days of|Tropic'],
  ['Lightning', 'Tampa|bolt|McQueen|strikes twice|bug'],
  ['Avalanche', 'Colorado|snow|Chevy|of mail'],
  ['Volcano', 'Hawaii|St. Helens|science fair|lava'],
  ['Desert', 'Mojave|dessert|Storm|island'],
  ['Glacier', 'park|ice|Montana|Bay'],
  ['Delta', 'airline|river|force|fraternity'],
  ['Gulf', 'Mexico|Stream|oil|War'],
  ['Coast', 'East|West|Guard|to coast|roller'],
  ['Harbor', 'Pearl|Baltimore|safe|Freight'],
  ['Island', 'Long|Rhode|Ellis|Treasure|Coney'],
  ['Coney', 'Island|dog|Cyclone|Detroit'],
  ['Boardwalk', 'Atlantic City|Monopoly|Empire|Jersey Shore'],
  ['Pier', 'Santa Monica|Navy|39|1 Imports'],
  ['Lighthouse', 'Hatteras|Maine|keeper|Woolf'],
  ['Trail', 'Oregon|Appalachian|mix|Blazers|Tears'],
  ['Dollar', 'bill|General|Store|Tree|sign|almighty'],
  ['Buck', 'Milwaukee|deer|dollar|Rogers|stops here'],
  ['Penny', 'coin|Lane|Lincoln|pinch|Big Bang'],
  ['Nickel', 'coin|Jefferson|back|Nickelodeon|Nickelback'],
  ['Dime', 'coin|Roosevelt|store|turn on a'],
  ['Quarter', 'coin|back|pounder|horse|quarters'],
  ['Mint', 'coin|julep|condition|Junior|toothpaste'],
  ['Fed', 'Reserve|Ex|agent|fed up'],
  ['Stock', 'market|car|chicken|laughing|Stockton'],
  ['Bond', 'savings|Barry|glue|bail|James'],
  ['Jackpot', 'lottery|slots|hit the|Powerball'],
  ['Casino', 'Vegas|Royale|Scorsese|Atlantic City'],
  ['Poker', 'Texas Hold em|face|fire|World Series'],
  ['Lottery', 'ticket|Shirley Jackson|Powerball|win the'],
  ['Bank', 'robber|river|piggy|of America|on it'],
  ['Steel', 'mill|Pittsburgh|Magnolias|Man of|Curtain'],
  ['Mill', 'sawmill|paper|treadmill|run of the'],
  ['Assembly', 'line|hall|required|of God'],
  ['Overalls', 'farmer|denim|OshKosh|painter'],
  ['Paycheck', 'Friday|Johnny|live to|direct deposit'],
  ['Coupon', 'clipping|Sunday paper|Extreme|bond'],
  ['Factory', 'Cheesecake|Willy Wonka|Records|farm'],
  ['Marine', 'Corps|One|biology|semper fi|Merchant'],
  ['Seal', 'Navy|animal|singer|Team Six|Easter'],
  ['Admiral', 'Navy|Ackbar|Nimitz|butterfly'],
  ['Sergeant', 'Pepper|drill|York|Slaughter'],
  ['Colonel', 'Sanders|Mustard|Kentucky|Klink'],
  ['General', 'Motors|Electric|Custer|Patton|Hospital'],
  ['Private', 'Ryan|eye|jet|property|Benjamin'],
  ['Tank', 'top|Sherman|Shark|think|gas'],
  ['Chopper', 'helicopter|motorcycle|get to the|pork chop'],
  ['Missile', 'Patriot|Cuban crisis|Minuteman|toe'],
  ['Minuteman', 'militia|missile|Lexington|Concord'],
  ['Redcoat', 'British|Revolution|lobsterback|coming'],
  ['Cannon', 'Civil War|ball|loose|Nick'],
  ['Fort', 'Knox|Sumter|Lauderdale|blanket|Worth'],
  ['Bunker', 'Hill|Archie|golf|doomsday'],
  ['Medal', 'of Honor|gold|Olympics|Freedom'],
  ['Salute', 'military|21-gun|I salute you|Your Shorts'],
  ['Taps', 'bugle|beer|tap dance|wiretap'],
  ['Navy', 'blue|Seal|beans|Old Navy|Yard'],
  ['Army', 'Navy game|Salvation|of one|ants|knife'],
  ['Air Force', 'One|Academy|Nike|Falcons'],
  ['Rosie', 'the Riveter|ODonnell|Perez|Jetsons'],
  ['Flag', 'Betsy Ross|Six Flags|red|capture the|football'],
  ['Star', 'Dallas|flag|Hollywood|Wars|Trek|lone'],
  ['Stripe', 'flag|zebra|Stripes|earn your|referee'],
  ['Torch', 'Liberty|Olympic|relay|blowtorch|Human'],
  ['Crown', 'Liberty|Royal|king|tooth|Vic'],
  ['Pledge', 'allegiance|furniture polish|drive|frat'],
  ['Jury', 'twelve|duty|rigged|Runaway'],
  ['Cabinet', 'executive|kitchen|filing|Caligari'],
  ['Bill', 'of Rights|dollar|duck|Nye|Buffalo'],
  ['Party', 'political|Tea|birthday|pooper|line'],
  ['Uncle', 'Sam|Buck|Toms Cabin|say uncle|Fester'],
  ['Sam', 'Uncle|Cooke|I Am|Yosemite|Walton|Malone'],
];
