// Americana pack, part 3 of 5: common nouns. Food, the house, the road, the
// town. These carry the most meanings, so they should be at least half of
// any board.
export default [
  ['Apple', 'pie|company|Big|Adam|Appleseed'],
  ['Pie', 'apple|chart|pizza|humble|3.14'],
  ['Burger', 'hamburger|King|Five Guys|veggie'],
  ['Hot Dog', 'Coney|Nathans|show-off|dachshund'],
  ['Barbecue', 'grill|ribs|sauce|Kansas City'],
  ['Grits', 'corn|Southern|True Grit|kiss my'],
  ['Gumbo', 'stew|okra|Louisiana|Cajun'],
  ['Cornbread', 'Southern|skillet|muffin|aint nothin wrong'],
  ['Biscuit', 'Southern|gravy|Seabiscuit|dog treat'],
  ['Gravy', 'biscuits|train|boat|Thanksgiving'],
  ['Turkey', 'bird|Thanksgiving|bowling|country|cold'],
  ['Pumpkin', 'pie|Halloween|spice|Cinderella'],
  ['Cranberry', 'sauce|juice|bog|band'],
  ['Peanut', 'butter|gallery|Planters|Peanuts'],
  ['Popcorn', 'movie|ceiling|kernel|Orville'],
  ['Pretzel', 'soft|Philly|logic|twist'],
  ['Bagel', 'New York|lox|zero|hole'],
  ['Donut', 'glazed|dozen|spare tire|hole'],
  ['Waffle', 'Belgian|House|indecision|iron'],
  ['Pancake', 'flapjack|IHOP|flat|stack'],
  ['Diner', 'Route 66|coffee|booth|Seinfeld'],
  ['Milkshake', 'diner|brings the boys|Shamrock|strawberry'],
  ['Soda', 'pop|fountain|baking|jerk'],
  ['Root Beer', 'float|A and W|barrel|sarsaparilla'],
  ['Lemonade', 'stand|when life gives you|pink|Beyonce'],
  ['Bourbon', 'whiskey|Street|Kentucky|dynasty'],
  ['Moonshine', 'whiskey|still|Prohibition|NASCAR'],
  ['Cocktail', 'drink|Tom Cruise|party|dress'],
  ['Jerky', 'beef|dried|road trip|movement'],
  ['Chili', 'cook-off|Cincinnati|pepper|dog|Red Hot'],
  ['Taco', 'Tuesday|Bell|truck|Doritos'],
  ['Nacho', 'cheese|Libre|average|not yo'],
  ['Lobster', 'Maine|roll|red|bisque|Rock Lobster'],
  ['Crab', 'Maryland|cake|Old Bay|hermit|Cancer'],
  ['Chowder', 'clam|Manhattan|New England|Boston'],
  ['Oyster', 'Rockefeller|pearl|the world is|Bay'],
  ['Catfish', 'fish|Mississippi|online fake|noodling'],
  ['Steak', 'T-bone|Omaha|stake|Philly'],
  ['Ribs', 'barbecue|Adam|tickle|prime'],
  ['Wing', 'Buffalo|chicken|airplane|West Wing|Red Wings'],
  ['Pickle', 'jar|ball|in a|dill'],
  ['Ketchup', 'Heinz|fries|catch up|tomato'],
  ['Mustard', 'yellow|cut the|gas|Colonel'],
  ['Mayo', 'Clinic|mayonnaise|County|Dukes'],
  ['Ranch', 'dressing|cattle|house|dude'],
  ['Cheesecake', 'New York|Factory|Golden Girls|pin-up'],
  ['Brownie', 'dessert|points|Girl Scout|camera'],
  ['Smore', 'campfire|marshmallow|graham|want some more'],
  ['Jelly', 'PB and J|bean|fish|Belly'],
  ['Cereal', 'breakfast|Cheerios|box|serial'],
  ['Candy', 'bar|corn|cane|Land|Man'],
  ['Gum', 'bubble|Bazooka|shoe|tree|boots'],
  ['Bacon', 'breakfast|Kevin|bits|bring home'],
  ['Cheese', 'American|head|say|big|cake'],
  ['Corn', 'cob|dog|maze|kernel|corny'],
  ['Pizza', 'New York|deep dish|Hut|Rat|party'],
  ['Sandwich', 'Earl|sub|hero|hoagie|knuckle'],
  ['Sub', 'sandwich|marine|way|substitute'],
  ['Coffee', 'Folgers|cup of joe|break|table'],
  ['Beer', 'pong|belly|root|cold one'],
  ['Keg', 'party|stand|beer|powder'],
  ['Porch', 'front|swing|light|pirate'],
  ['Yard', 'sale|stick|front|junk|Scotland'],
  ['Garage', 'band|sale|door|rock'],
  ['Driveway', 'basketball|hoop|shovel|parked'],
  ['Lawn', 'mower|gnome|keep off|chair'],
  ['Mailbox', 'letters|flag|Money|baseball bat'],
  ['Quilt', 'patchwork|grandma|Amish|bee'],
  ['Rocker', 'chair|rock star|Kennedy|Knute'],
  ['Attic', 'flowers|bats|storage|Greece'],
  ['Basement', 'rec room|band|dweller|bargain'],
  ['Barn', 'raising|door|red|owl|burner'],
  ['Silo', 'grain|missile|farm|data'],
  ['Fence', 'white picket|Fences|on the|Frost'],
  ['Picket', 'fence|line|strike|Pickett'],
  ['Suburb', 'Levittown|cul-de-sac|sprawl|Suburbia'],
  ['Main Street', 'small town|Sinclair Lewis|Disney|versus Wall Street'],
  ['Courthouse', 'square|wedding|Mockingbird|steps'],
  ['Firehouse', 'dog|Subs|five|pole'],
  ['Schoolhouse', 'Rock|one-room|red|bell'],
  ['Drugstore', 'cowboy|soda fountain|pharmacy|corner'],
  ['Drive-In', 'movie|burger stand|speaker|car'],
  ['Motel', '6|Bates|neon|vacancy'],
  ['Trailer', 'park|movie|hitch|Airstream'],
  ['Camper', 'RV|Happy|van|Boy Scout'],
  ['Cabin', 'log|fever|pressure|Uncle Tom'],
  ['Farm', 'Old MacDonald|Animal|team|State|Aid'],
  ['Tractor', 'John Deere|pull|Supply|trailer'],
  ['Pickup', 'truck|line|game|artist'],
  ['Truck', 'stop|monster|food|keep on truckin'],
  ['Highway', 'interstate|to Hell|patrol|61'],
  ['Turnpike', 'Pennsylvania|toll|Ohio|New Jersey'],
  ['Exit', 'ramp|sign|stage left|strategy'],
  ['Pump', 'gas|iron|shoe|heart|it up'],
  ['Tailgate', 'truck|party|parking lot|too close'],
  ['Parade', 'Rose|float|rain on my|Thanksgiving'],
  ['Fireworks', 'Fourth|Katy Perry|sparks|finale'],
  ['Picnic', 'basket|table|ants|no picnic'],
  ['Cookout', 'grill|Fourth|burgers|block party'],
  ['Backyard', 'barbecue|Baseball|wrestling|in your own'],
];
