// Americana pack, part 1 of 5: places. Every word carries at least two hooks,
// written as a pipe-separated string. The hooks are for the editor, not the
// game: they are the proof that the word can be clued more than one way.
export default [
  ['Washington', 'president|state|city|bridge|dollar bill'],
  ['Georgia', 'state|country|peach|Ray Charles'],
  ['Virginia', 'state|Woolf|Slim|is for lovers'],
  ['Montana', 'state|Joe|Hannah|Big Sky'],
  ['Indiana', 'state|Jones|Hoosiers|Pacers'],
  ['Kansas', 'state|Dorothy|band|Jayhawks'],
  ['Nevada', 'state|silver|desert|Vegas'],
  ['Phoenix', 'city|bird|Suns|rising'],
  ['Dallas', 'city|Cowboys|TV show|JFK'],
  ['Denver', 'city|Broncos|mile high|omelet'],
  ['Austin', 'city|Powers|Stone Cold|SXSW'],
  ['Columbus', 'city|explorer|Day|Crew'],
  ['Orlando', 'city|Disney|Bloom|Magic'],
  ['Charlotte', 'city|Hornets|Web|name'],
  ['Cleveland', 'city|Browns|Grover|rocks'],
  ['Houston', 'city|Astros|Whitney|we have a problem'],
  ['Buffalo', 'city|animal|wings|Bills|nickel'],
  ['Boston', 'city|Tea Party|band|terrier|cream pie'],
  ['Memphis', 'city|Egypt|Elvis|blues|barbecue'],
  ['Nashville', 'city|country music|hot chicken|Predators'],
  ['Vegas', 'casino|Strip|what happens|Elvis'],
  ['Hollywood', 'movies|sign|Boulevard|Florida|Walk of Fame'],
  ['Broadway', 'theater|street|Namath|musical'],
  ['Alamo', 'mission|remember|rental car|Texas'],
  ['Alcatraz', 'prison|island|the Rock|escape'],
  ['Capitol', 'dome|Hill|Records|Reef'],
  ['Pentagon', 'building|shape|military|papers'],
  ['Everglades', 'swamp|gator|airboat|Florida'],
  ['Rockies', 'mountains|Colorado|baseball|Rocky'],
  ['Yosemite', 'park|Sam|El Capitan|Half Dome'],
  ['Yellowstone', 'park|geyser|TV show|bison'],
  ['Niagara', 'falls|barrel|honeymoon|Ontario'],
  ['Delaware', 'state|river|crossing|corporations'],
  ['Erie', 'lake|canal|Pennsylvania|eerie'],
  ['Manhattan', 'island|cocktail|Project|Kansas|clam chowder'],
  ['Brooklyn', 'borough|bridge|Dodgers|Beckham|accent'],
  ['Harlem', 'neighborhood|Globetrotters|Renaissance|Shake'],
  ['Bronx', 'borough|cheer|Yankees|zoo'],
  ['Chicago', 'city|band|musical|deep dish|Bulls|Fire'],
  ['Detroit', 'city|Motown|motor|Lions|Pistons'],
  ['Philly', 'cheesesteak|Eagles|cream cheese|Rocky'],
  ['Pittsburgh', 'Steelers|steel|bridges|Penguins|three rivers'],
  ['Miami', 'city|Vice|Heat|Dolphins|beach'],
  ['Seattle', 'city|rain|coffee|grunge|Space Needle'],
  ['Portland', 'Oregon|Maine|Trail Blazers|roses|weird'],
  ['Baltimore', 'Ravens|Orioles|crab|Poe|The Wire'],
  ['Atlanta', 'Braves|Falcons|Coca-Cola|airport|Olympics'],
  ['Salem', 'witches|Oregon|Massachusetts|trials'],
  ['Plymouth', 'Rock|car|Pilgrims|colony'],
  ['Gettysburg', 'battle|address|Lincoln|Pennsylvania'],
  ['Mississippi', 'river|state|counting seconds|Delta'],
  ['Missouri', 'state|river|show me|compromise'],
  ['Colorado', 'state|river|Rockies|Avalanche|Rapids'],
  ['Arizona', 'state|iced tea|Cardinals|Diamondbacks|battleship'],
  ['Texas', 'state|hold em|toast|Rangers|everything is bigger'],
  ['Alaska', 'state|Airlines|cruise|Purchase|baked'],
  ['Hawaii', 'state|Five-O|pizza|aloha|volcano'],
  ['Jersey', 'state|shirt|Shore|cow|Boys'],
  ['Carolina', 'Panthers|Hurricanes|Reaper|blue|Tar Heels'],
  ['Dakota', 'state|Fanning|badlands|Rushmore'],
  ['Vermont', 'state|maple syrup|Ben and Jerry|skiing'],
  ['Maine', 'state|lobster|Stephen King|battleship|coon cat'],
  ['Utah', 'state|Jazz|Salt Lake|Olympics|beach'],
  ['Oregon', 'state|Trail|Ducks|dysentery'],
  ['Idaho', 'state|potato|panhandle|Boise'],
  ['Kentucky', 'state|Derby|fried chicken|bourbon|bluegrass'],
  ['Tennessee', 'state|Williams|Titans|whiskey|Volunteers'],
  ['Alabama', 'state|band|Crimson Tide|Sweet Home|Shakes'],
  ['Louisiana', 'state|Purchase|hot sauce|bayou|Cajun'],
  ['Michigan', 'state|lake|Wolverines|mitten|Avenue'],
  ['Minnesota', 'state|Vikings|Twins|lakes|Fats'],
  ['Nebraska', 'state|corn|Springsteen|Cornhuskers'],
  ['Oklahoma', 'state|musical|Sooners|Thunder|OK'],
  ['Wisconsin', 'state|cheese|Packers|Badgers|dairy'],
  ['Iowa', 'state|corn|caucus|Field of Dreams|Hawkeyes'],
  ['Ohio', 'state|Buckeyes|round on the ends|river|State'],
  ['Reno', 'city|biggest little city|911|divorce'],
  ['Tahoe', 'lake|Chevy|skiing|Godfather'],
  ['Napa', 'valley|wine|cabbage|auto parts'],
  ['Malibu', 'beach|rum|Barbie|Chevy'],
  ['Aspen', 'town|tree|skiing|Dumb and Dumber'],
  ['Cape', 'Cod|Canaveral|Superman|Fear|Hatteras'],
  ['Canyon', 'Grand|Bryce|echo|ranch'],
  ['Prairie', 'grass|Little House|dog|schooner'],
  ['Bayou', 'swamp|Louisiana|Blue Bayou|Cajun|gator'],
  ['Badlands', 'park|Springsteen|Dakota|movie'],
  ['Beltway', 'highway|DC|insider|traffic'],
  ['Mall', 'shopping|National|food court|of America'],
  ['Rushmore', 'mountain|four presidents|Wes Anderson|Dakota'],
  ['Liberty', 'Bell|Statue|Island|Mutual|Valance|give me'],
  ['Independence', 'Day|Hall|Missouri|Declaration|movie'],
  ['Union', 'Civil War|station|labor|Jack|Square'],
  ['Dixie', 'South|cups|whistle|land'],
  ['Yankee', 'New York|Doodle|Stadium|Northerner|Candle'],
  ['Frontier', 'West|Airlines|Star Trek|final'],
  ['Heartland', 'Midwest|TV show|corn|America'],
  ['Wall Street', 'finance|bull|movie|Journal'],
  ['Route 66', 'highway|kicks|Cars|Mother Road'],
  ['Silicon Valley', 'tech|HBO|startups|Stanford'],
  ['Big Apple', 'New York|nickname|circus|sticker'],
];
